#!/usr/bin/env python3
import sys

from lib.cli import Cli

def checkArgument():
    if len(sys.argv) != 5:
        print("http - Connect a switch through HTTP protocol")
        print("Usage: poe-get-status host user password port")
        print("       port must be a number between 1 and 12")
        sys.exit(0)

def parseArgument():
    return sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]

if __name__ == "__main__":
    checkArgument()
    host, user, password, ports = parseArgument()

    if Cli.testConnection('https', host):
        cli = Cli('https', host)
    else:
        if Cli.testConnection('http', host):
            cli = Cli('http', host)
        else:
            print("Error: Cannot connect to remote host through HTTP and HTTPS.")
            sys.exit(0)

    if not cli.login(user, password):
        print("Cannot login. Username or password are wrong")
        sys.exit(0)

    try:
        poe_status = cli.getPoeStatus([int(i) for i in ports.split(",")])
        print(poe_status)
    except Exception as e:
        print("An error occured: " + str(e))
    finally:
        cli.logout()
        cli.close()
